// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdbE6OFYZm28PQ1wm7HIuuZunC1Cb5UJU',
    appId: '1:558968875125:android:e00373b6a5c5e9a0e3f03c',
    messagingSenderId: '558968875125',
    projectId: 'digital-health-care-app',
    databaseURL: 'https://digital-health-care-app-default-rtdb.firebaseio.com',
    storageBucket: 'digital-health-care-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjy5Rsp-qY-uF8v_Wt2xcKzAmsAtWWIUk',
    appId: '1:558968875125:ios:4f809e1e27bfc5dee3f03c',
    messagingSenderId: '558968875125',
    projectId: 'digital-health-care-app',
    databaseURL: 'https://digital-health-care-app-default-rtdb.firebaseio.com',
    storageBucket: 'digital-health-care-app.appspot.com',
    iosBundleId: 'com.example.finalYearProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjy5Rsp-qY-uF8v_Wt2xcKzAmsAtWWIUk',
    appId: '1:558968875125:ios:91607fdea0c1e466e3f03c',
    messagingSenderId: '558968875125',
    projectId: 'digital-health-care-app',
    databaseURL: 'https://digital-health-care-app-default-rtdb.firebaseio.com',
    storageBucket: 'digital-health-care-app.appspot.com',
    iosBundleId: 'com.example.digitalHealthcareApp.RunnerTests',
  );
}
